list:  ~/plugins/october/test/models/user/columns.yaml
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 10
readOnly: false
modelClass: October\Test\Models\User
toolbar:
    buttons: ~/plugins/october/test/reportwidgets/poststats/partials/_list_toolbar.htm
    search:
        prompt: backend::lang.list.search_prompt